package ${cfg.baseMapperPackage};

import ${cfg.commonMapperPackage}.BaseMapper;
import ${cfg.baseDbBeanPackage}.${table.beanName};

/**
warning
This file is generated by code-generator
Please DO NOT modify this file
**/
public interface ${table.beanName}BaseMapper extends BaseMapper<${table.beanName}> {

}